
g++ -Wall $1 $2 -D__LINUX__ -D__MAC__ -D__64__ -D__CONSOLE__ -D__CAN__ -D__SCAN__ -lc -lpthread \
  ../KIpSocket.cpp \
  ../KThread.cpp \
  ../KCriticalSection.cpp \
  ../KCanDriver.cpp \
  ../KComm.cpp \
  ../KCanCommDriver.cpp \
  ../KRPiCanDriver.cpp \
  ../KCanServer.cpp \
  ../KStream.cpp \
  ../NUtils.cpp \
  ../NCanUtils.cpp \
  ../KElsterTable.cpp \
  ../KScanTable.cpp \
  ../KCanElster.cpp \
  ../KSniffedFrame.cpp \
  ../KCanTcpDriver.cpp \
  ../KTcpClient.cpp \
  -o can_scan