# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package elster_perl;
use base qw(Exporter);
use base qw(DynaLoader);
package elster_perlc;
bootstrap elster_perl;
package elster_perl;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package elster_perl;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package elster_perl;

*geterrormsg = *elster_perlc::geterrormsg;
*getvaluemsg = *elster_perlc::getvaluemsg;
*getvalue = *elster_perlc::getvalue;
*setvalue = *elster_perlc::setvalue;
*setbits = *elster_perlc::setbits;
*clrbits = *elster_perlc::clrbits;
*getstring = *elster_perlc::getstring;
*setstring = *elster_perlc::setstring;
*getname = *elster_perlc::getname;
*gettype = *elster_perlc::gettype;
*toggle_trace = *elster_perlc::toggle_trace;
*setdev = *elster_perlc::setdev;
*setcs = *elster_perlc::setcs;
*set_can232 = *elster_perlc::set_can232;
*initcan = *elster_perlc::initcan;
*undef = *elster_perlc::undef;
*setsniffedframe = *elster_perlc::setsniffedframe;
*getsniffedvalue = *elster_perlc::getsniffedvalue;

# ------- VARIABLE STUBS --------

package elster_perl;

1;
