/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_ELSTER_PERL_H
#define PHP_ELSTER_PERL_H

extern zend_module_entry elster_perl_module_entry;
#define phpext_elster_perl_ptr &elster_perl_module_entry

#ifdef PHP_WIN32
# define PHP_ELSTER_PERL_API __declspec(dllexport)
#else
# define PHP_ELSTER_PERL_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(elster_perl);
PHP_MSHUTDOWN_FUNCTION(elster_perl);
PHP_RINIT_FUNCTION(elster_perl);
PHP_RSHUTDOWN_FUNCTION(elster_perl);
PHP_MINFO_FUNCTION(elster_perl);

ZEND_NAMED_FUNCTION(_wrap_geterrormsg);
ZEND_NAMED_FUNCTION(_wrap_getvaluemsg);
ZEND_NAMED_FUNCTION(_wrap_getvalue);
ZEND_NAMED_FUNCTION(_wrap_setvalue);
ZEND_NAMED_FUNCTION(_wrap_setbits);
ZEND_NAMED_FUNCTION(_wrap_clrbits);
ZEND_NAMED_FUNCTION(_wrap_getstring);
ZEND_NAMED_FUNCTION(_wrap_setstring);
ZEND_NAMED_FUNCTION(_wrap_getname);
ZEND_NAMED_FUNCTION(_wrap_gettype);
ZEND_NAMED_FUNCTION(_wrap_toggle_trace);
ZEND_NAMED_FUNCTION(_wrap_setdev);
ZEND_NAMED_FUNCTION(_wrap_setcs);
ZEND_NAMED_FUNCTION(_wrap_set_can232);
ZEND_NAMED_FUNCTION(_wrap_initcan);
ZEND_NAMED_FUNCTION(_wrap_undef);
ZEND_NAMED_FUNCTION(_wrap_setsniffedframe);
ZEND_NAMED_FUNCTION(_wrap_getsniffedvalue);
ZEND_NAMED_FUNCTION(_wrap_getfirstsniffedvalue);
#endif /* PHP_ELSTER_PERL_H */
